### ISSUE TITLE
Document units

### ISSUE THREAD

**Issue by lukepighetti** [soloam/ha-pid-controller#29]
It would be very helpful if we could document the units of P/I/D and also what the defaults are (P of 0 appears to be ∞, not 0 for example)

https://www.youtube.com/watch?v=IB1Ir4oCP5k

**Comment by soloam** [comment]
In PID there are no defaults! The values are the bases of the PID system, and it's value is the part that they take on the system.

I'm working on a auto runner, that should be OK for determination of the bases of the values. It's still a work in progress.

**Comment by hannut** [comment]
Are the i and d seconds as in the example or measurement points?

**Comment by apazureck** [comment]
Hi,

I think @hannut has a legitimate question here, I was asking myself. As I want to control my central heating, the P and Ds are more in the range of an hour or two. So I tried to set them as seconds here and did not connect the output to my target flow temperature (I hope that's the correct english word for the German "Vorlauftemperatur"). So the controller does not actually set the value. Then this happened:

![grafik](https://user-images.githubusercontent.com/14858596/208609087-b7b012a0-b49b-493a-adbd-102b605672c0.png)

Those are my settings:

```yaml
platform: pid_controller
name: ETA PID Vorlauf Controller

set_point: "{{state_attr('climate.wohnzimmer_master', 'temperature') | float}}"
entity_id: sensor.ts_wohnzimmer_temperature
precision: 1
sample_time: 60
maximum: 70
unit_of_measurement: °C
p: 2
i: 10800 // Seconds
d: 2700 // Seconds
```
So I will now convert them to multiples of the ´sample_time´ value and see what happens.
