### ISSUE TITLE
Example config: Values will reset on HA restart

### ISSUE THREAD

**Issue by RubenKelevra** [soloam/ha-pid-controller#3]
I set some values in Lovelace and restarted HA.

All values were reset to their initial/default values.

I don't think that's supposed to be this way?

**Comment by soloam** [comment]
I don't understand what you mean! The component will get the value's Home Assistant supplies, if they are reset on restart nothing can be supplied.

**Comment by RubenKelevra** [comment]
Well I've added the values via configuration.yaml and rebooted HA.

Then I configured your component by changing the values.

After a while I rebooted HA again, and all values changed back to their default value - as if HA won't store them permanently.

**Comment by soloam** [comment]
To edit the value's and keep them between restarts you need to work with input_numbers and you have to configure the Home Assistant recorder. . This is not related with this component.

**Comment by RubenKelevra** [comment]
Not sure how the default config is not related to the component 🤔

I wasn't expecting that the default config requires me to reenter the settings on each HA restart.

That might be okay for testing or something like that, but shouldn't be the recommended installation.

**Comment by soloam** [comment]
I guess I can't understand what you mean by default config! It would be better to Post your config to see what's the problem

**Comment by soloam** [comment]
I think I've seen your problem, did you set the `initial` in the input_number like I had in my example?

```yaml
input_number:
  sample_time:
    name: Sample Time
    initial: 0
    min: 0
    max: 30
    step: 1
```

You should remove the `initial`:

```yaml
input_number:
  sample_time:
    name: Sample Time
    min: 0
    max: 30
    step: 1
```
