### ISSUE TITLE
Output artifacts when input value becomes unavailable

### ISSUE THREAD

**Issue by lukepighetti** [soloam/ha-pid-controller#30]
If an input value becomes unavailable, `ha-pid-controller` defaults to 100% output. It would be nice to either handle this in `ha-pid-controller` or provide documentation for how to filter these values

**Comment by soloam** [comment]
You can filter all the values with templates! All the fields can handle templating. You could do this, but I agree that the controller should handle this.

Tks

**Comment by lukepighetti** [comment]
How would one do that with a template? Is there some way to use previous?

**Comment by soloam** [comment]
You could turn off the pid if the variable of the input is unavailable.

But I agree that the pid should handle this! I'll put it on my to-do list.

**Comment by lukepighetti** [comment]
Ah, might be worth mentioning here that I'm not controlling something solid state like a solid state relay. I'm controlling a loud, slow moving linear servo. So when the pid is turned off, it moves the solenoid. And when it comes back on, it moves it back into place. Need to keep the signal clean for the sake of that type of equipment (and the hassle of listening to it)

**Comment by lukepighetti** [comment]
Something that might help other folks, if you're using ESPHome, you can filter out nan values like so. Will have to wait to see if it resolves the issue for me

```yaml
esphome:
  name: woodstove

# ...

sensor:
  - platform: max6675
    # ...
    filters:
      filter_out: nan

```

**Comment by lukepighetti** [comment]
In the process of trying this out

```yaml
  - platform: template
    sensors:
      woodstove_flue_temperature_filtered:
        friendly_name: "Woodstove Flue Temperature Filtered"
        unit_of_measurement: "°F"
        value_template: >
          {% if states('sensor.woodstove_flue_temperature') in ['unavailable', 'unknown', 'none'] %}
            {{ states('sensor.woodstove_flue_temperature_filtered') }}
          {% else %}
            {{ states('sensor.woodstove_flue_temperature') }}
            {% endif %}
```
