### ISSUE TITLE
odd reset behavior when trying to adjust P and I

### ISSUE THREAD

**Issue by apazureck** [soloam/ha-pid-controller#38]
Hi,

For some reason the controller jumps back to min value when running for some time:

![grafik](https://user-images.githubusercontent.com/14858596/209401236-4d0ee98e-c0d0-4082-8b87-fc7b236c1436.png)

My settings:

P = 2
I = 0.01
D = 0
minimum = 25
maximum = 60

My settings:

```yaml
set_point: "{{state_attr('climate.wohnzimmer_master', 'temperature')}}"
entity_id: input_number.eta_stellgroesse_vorlauf
precision: 0.01
minimum: "{{states('input_number.eta_pid_regler_minimum')}}"
maximum: "{{states('input_number.eta_pid_regler_maximum')}}"
unit_of_measurement: °C
p: "{{states('input_number.eta_pid_regler_p')}}"
i: "{{states('input_number.eta_pid_regler_i')}}"
d: "{{states('input_number.eta_pid_regler_d')}}"
```

My scenario:

Control my overall central heating temperature. As the flow temperature is higher than the room temperature I need the I part the most. For some reason it integrates up to 10 and then it resets the whole sensor to the minimum value of 25. Thus the temperature never rises correctly.

What could cause this behavior?

I am using version 1.1.5 (the latest on hacs)
