### ISSUE TITLE
Adding Multiple PID Controllers

### ISSUE THREAD

**Issue by spooner123-ha** [soloam/ha-pid-controller#56]
Hi, thanks for the great controller.
Everything works fine with one instance.

I would like to run multiple PID controllers in parallel.
So far I was not able to create more than one Sensor.

Any advice would be much appreciated.
Cheers!

**Comment by soloam** [comment]
Hell, thank you for the feedback! Can you post the config for both controllers? The sensor declaration is independently, so you would have to add both sensors.

**Comment by spooner123-ha** [comment]
`
pid_controller:

sensor:
    platform: pid_controller
    name: pid_thermometer_kroeten
    enabled: '{{ states("input_boolean.pid_th_enabled") }}'
    set_point: '{{ states("input_number.pid_th_set_point") }}'
    p: '{{ states("input_number.pid_th_proportional") }}'
    i: '{{ states("input_number.pid_th_integral") }}'
    d: '{{ states("input_number.pid_th_derivative") }}'
    entity_id: input_number.pid_th_reading
    invert: '{{ states("input_boolean.pid_th_invert") }}'
    precision: '{{ states("input_number.pid_th_precision") }}'
    minimum: '{{ states("input_number.pid_th_minimum") }}'
    maximum: '{{ states("input_number.pid_th_maximum") }}'
    round: '{{ states("input_select.pid_th_round") }}'
    sample_time: '{{ states("input_number.pid_th_sample_time") }}'
    windup: '{{ states("input_number.pid_th_windup") }}'

sensor1:
    platform: pid_controller
    name: pid_light_kroeten
    enabled: '{{ states("input_boolean.pid_light_enabled") }}'
    set_point: '{{ states("input_number.pid_light_set_point") }}'
    p: '{{ states("input_number.pid_light_proportional") }}'
    i: '{{ states("input_number.pid_light_integral") }}'
    d: '{{ states("input_number.pid_light_derivative") }}'
    entity_id: input_number.pid_light_reading
    invert: '{{ states("input_boolean.pid_light_invert") }}'
    precision: '{{ states("input_number.pid_light_precision") }}'
    minimum: '{{ states("input_number.pid_light_minimum") }}'
    maximum: '{{ states("input_number.pid_light_maximum") }}'
    round: '{{ states("input_select.pid_light_round") }}'
    sample_time: '{{ states("input_number.pid_light_sample_time") }}'
    windup: '{{ states("input_number.pid_light_windup") }}'
`

I try to achieve to have two sensors separate from each other

**Comment by spooner123-ha** [comment]
Hi,

i fixed it...
yaml is new to me, did know the "-" makes all the difference

```
sensor:
  - platform: pid_controller
    name: pid_thermometer_kroeten
    enabled: '{{ states("input_boolean.pid_th_enabled") }}'
    set_point: '{{ states("input_number.pid_th_set_point") }}'
    p: '{{ states("input_number.pid_th_proportional") }}'
    i: '{{ states("input_number.pid_th_integral") }}'
    d: '{{ states("input_number.pid_th_derivative") }}'
    entity_id: input_number.pid_th_reading
    invert: '{{ states("input_boolean.pid_th_invert") }}'
    precision: '{{ states("input_number.pid_th_precision") }}'
    minimum: '{{ states("input_number.pid_th_minimum") }}'
    maximum: '{{ states("input_number.pid_th_maximum") }}'
    round: '{{ states("input_select.pid_th_round") }}'
    sample_time: '{{ states("input_number.pid_th_sample_time") }}'
    windup: '{{ states("input_number.pid_th_windup") }}'
  - platform: pid_controller
    name: pid_light_kroeten
    enabled: '{{ states("input_boolean.pid_light_enabled") }}'
    set_point: '{{ states("input_number.pid_light_set_point") }}'
    p: '{{ states("input_number.pid_light_proportional") }}'
    i: '{{ states("input_number.pid_light_integral") }}'
    d: '{{ states("input_number.pid_light_derivative") }}'
    entity_id: input_number.pid_light_reading
    invert: '{{ states("input_boolean.pid_light_invert") }}'
    precision: '{{ states("input_number.pid_light_precision") }}'
    minimum: '{{ states("input_number.pid_light_minimum") }}'
    maximum: '{{ states("input_number.pid_light_maximum") }}'
    round: '{{ states("input_select.pid_light_round") }}'
    sample_time: '{{ states("input_number.pid_light_sample_time") }}'
    windup: '{{ states("input_number.pid_light_windup") }}'

```
