### ISSUE TITLE
No perceivable action - does not seem to execute.

### ISSUE THREAD

**Issue by DrConradInTheHouse** [soloam/ha-pid-controller#60]
I created the additional config from your example. Rebooted. The integration is added (but cannot be managed through the GUI as expected). There is nothing logged to homeassistant.log whatsoever from this. No errors and the rest of HA runs perfectly. The lovelace card shows no output (0.0). Does it actually do anything? 
Yes of course it's enabled, there are no diags to download from the integration as others have, and no way of debugging.

![Image](https://github.com/user-attachments/assets/482fe4fc-1453-4ae2-91c3-84d7d8e4d600)

configuration.yaml (to be tidied up later moving PID to a package)
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml

script: !include scripts.yaml

scene: !include scenes.yaml

#--DAZ 10.10.2023

logger: !include logger.yaml

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 
    - 172.29.0.0/24 # docker network gateway
    - 127.0.0.0/24
    
#--10.10.23

homeassistant:
  packages: !include_dir_merge_named packages/
 

pid_controller:

sensor:
  - platform: pid_controller
    name: Pump PID output
    enabled: '{{ states("input_boolean.enabled") }}'
    set_point: '{{ states("input_number.set_point") }}'
    p: '{{ states("input_number.proportional") }}'
    i: '{{ states("input_number.integral") }}'
    d: '{{ states("input_number.derivative") }}'
    entity_id: input_number.reading
    #entity_id: sensor.meter_plus_da53_lounge
    invert: '{{ states("input_boolean.invert") }}'
    precision: '{{ states("input_number.precision") }}'
    minimum: '{{ states("input_number.minimum") }}'
    maximum: '{{ states("input_number.maximum") }}'
    round: '{{ states("input_select.round") }}'
    sample_time: '{{ states("input_number.sample_time") }}'
    windup: '{{ states("input_number.windup") }}'

input_boolean:
  pid_invert:
    name: Invert
    initial: no
  pid_enabled:
    name: Enabled

input_select:
  pid_round:
    initial: Round
    options:
      - Floor
      - Ceil
      - Round

input_number:
  pid_sample_time:
    name: Sample Time
    initial: 0
    min: 0
    max: 30
    step: 1

  pid_minimum:
    name: Minimum
    initial: 0
    min: 0
    max: 5
    step: 1

  pid_maximum:
    name: Maximum
    initial: 5
    min: 0
    max: 20
    step: 1

  pid_temp_reading:
    name: Temp Reading
    initial: 0
    min: 0
    max: 30
    step: 1

  pid_set_point:
    name: Set Point
    initial: 15
    min: 0
    max: 30
    step: 1

  pid_proportional:
    name: Proportional
    initial: 0
    min: 0
    max: 10
    step: 0.01

  pid_integral:
    name: Integral
    initial: 0
    min: 0
    max: 10
    step: 0.01

  pid_derivative:
    name: Derivative
    initial: 0
    min: 0
    max: 10
    step: 0.01

  pid_precision:
    name: Precision
    initial: 2
    min: 0
    max: 10
    step: 1

  pid_windup:
    name: Windup
    initial: 0
    min: 0
    max: 30
    step: 1

```
